POST http://localhost:3000/api/generate

{
    "prompt": "Generate three sets of primary, secondary, and tertiary color based on the description and category provided. Provide only the hex codes for the color of each set, labeled as 1. and 2. respectively. The description is 'app that helps users to buy cupcake' and the category is 'Shopping'.The colors should be in compliance with ATSI communities.."
}