POST http://localhost:3002/api/generate

{
    "prompt": "I need you to act as a UX designer and identify the 3 pain points that has ATSI communities as target users. The description of the app is \"App that helps users to share photos\" and can you build 2 real-time persona based on that? limit the pain points in 60 characters and persona to 100 characters that should include goals etc.."
}